# Generated by Django 4.0.6 on 2022-07-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_team_delete_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=250)),
                ('pimg', models.ImageField(upload_to='pics')),
                ('pdesc', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
